version: '3.9'
services:
  spaces:
    build:
      context: server
      dockerfile: spaces.Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - MINIO_HOST=minio:9000
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - minio
    restart: always
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
  minio:
    image: minio/minio:RELEASE.2022-04-01T03-41-39Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
